server:
  host: "0.0.0.0"
  port: 8081
  
database:
  type: sqlite
  path: "./data/agents.db"
  
llm:
  providers:
    openai:
      api_key: "${OPENAI_API_KEY}"
      base_url: "https://api.openai.com/v1"
    anthropic:
      api_key: "${ANTHROPIC_API_KEY}"
      base_url: "https://api.anthropic.com"
    mistral:
      api_key: "${MISTRAL_API_KEY}"
      base_url: "https://api.mistral.ai"
    grok:
      api_key: "${GROK_API_KEY}"
      base_url: "https://api.x.ai"
    ollama:
      base_url: "http://localhost:11434"

logging:
  level: info
  format: json

context:
  strategies:
    last_n:
      default_count: 10
    sliding_window:
      window_size: 5
      overlap: 2
    summarize:
      summary_model: "gpt-3.5-turbo"
      max_context_length: 20